# For more information about the available options please visit: http://go/backstage (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/ECS-Network-Racing-Sample
    backstage.io/techdocs-ref: dir:.
  name: ECS-Network-Racing-Sample
  description: "ECS multiplayer racing sample to showcase using Unity Entities and netcode with best practices"
  labels:
    costcenter: "5018"
  tags:
    - planned-public
spec:
  type: library
  lifecycle: production
  owner: unity-technologies/dots-qe
